### ISSUE TITLE
prometheus can't collect metrics, target is always down

### ISSUE THREAD

**Issue by Artemmkin** [prometheus/mysqld_exporter#151]
Hey guys! I'm sorry to bother you but I faced with the problem that I don't know how to solve. 
The thing is that my prometheus can't collect metrics from mysql_exporter, that is it shows that the target is always down (context deadline exceeded). I tried playing with the scrape time in prometheus config, changing it from 4 to 60 seconds and it still didn't work. It looks like myslq_exporter is working, 'cause I can see the metrics from inside another containers in my overlay network (http://db-exporter:9104/metrics). I have no idea what is wrong with it. I attach my docker-compose file and prometheus config. Hopefully, you'll be able to help me out, because I'm stuck here :( 
```yml
version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    networks:
      - back-tier
  prometheus:
    image: artemkin/blah
    container_name: prometheus
    environment:
     - constraint:node==artem-master
    volumes:
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - db-exporter
      - cadvisor1
    networks:
      - back-tier
  db-exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: root:123@(db:3306)/
    depends_on:
      - db
    expose:
      - 9104
    networks:
      - back-tier
  node-exporter1:
    image: prom/node-exporter
    environment:
     - constraint:node==artem-slave1
    expose:
      - 9100
    networks:
      - back-tier
  cadvisor1:
    image: google/cadvisor
    environment:
      - constraint:node==artem-slave1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - back-tier
networks:
  back-tier:
    driver: overlay
```
artemkin/blah is just prom/prometheus container where I put this prometheus config
```yml
# my global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-project'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 6s
    static_configs:
         - targets: ['db-exporter:9104','cadvisor1:8080','node-exporter1:9100']
```
other exporters like node-exporter or cadvisor work perfectly. I have no idea what is wrong with this one.
