### ISSUE TITLE
Collector Flags in docker-compose file

### ISSUE THREAD

**Issue by quanghnn** [prometheus/mysqld_exporter#430]
How can I do it?

**Comment by everflux** [comment]
This is a support question, example stated below, issue can be closed.

Example:

```
  mysqld-exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: exporter:exporter@(mariadb:3306)/
    ports:
      - "9104:9104"
    command:
    - "--collect.global_status"
    - "--collect.global_variables"
```
