### ISSUE TITLE
Error 1045: Access denied for user

### ISSUE THREAD

**Issue by fanhualei** [prometheus/mysqld_exporter#440]
lookat: https://github.com/prometheus/mysqld_exporter/issues/137 

I have a very similar issue right now.

"Error pinging mysqld: Error 1045: Access denied for user '"exporter'@'my-monitor-pro_mysql-exporter_1.myapp_default' (using password: YES)" source="exporter.go:146"

```
version: '2'
services:

  mysql_db:
    image: "mysql:5.7.15"
    container_name: mysql_db
    ports:
     - "3306:3306"
    volumes:
     - ./mysql_db:/etc/mysql/conf.d
    environment:
     - MYSQL_ROOT_PASSWORD=pass
     - MYSQL_DATABASE=mydb
     - MYSQL_USER=myuser
     - MYSQL_PASSWORD=mypass
    command: --lower-case-table-names=1 --performance_schema

  #
  # Prometheus
  #

  prometheus_mysql:
    image: "prom/mysqld-exporter:v0.9.0"
    container_name: prometheus_mysql
    depends_on: 
    - mysql_db
    ports:
     - "9104:9104"
    environment:
    - DATA_SOURCE_NAME="root:pass@(mysql_db:3306)/performance_schema" 
```
