### ISSUE TITLE
additional label for generated metrics

### ISSUE THREAD

**Issue by mellonedain** [prometheus/mysqld_exporter#466]
I have similar problem as described here: https://github.com/prometheus/mysqld_exporter/issues/452
But in my case all configurations are in distributed system. All exporters are handled by one simple Prometheus job - get metrics for all:
```
mysqld-exporter:
      scrape_interval: "30s"
      dns_sd_configs:
        - names:
            - mysqld-exporter.service.consul
```

All are running in Marathon - Mesos outside the system. Every restart e.g. IP is changed.

### Proposition

In my case the simplest solution to will be configurable from command line for all generated metrics additional label. For example `cluster: mysql-1`. This solution allow me identify my MySQL instances in Grafana directly for all metrics in very simple way.

Can it be possible in some nearest future?
