### ISSUE TITLE
Invalid metric type "ocap_thrcnt_limit untyped"

### ISSUE THREAD

**Issue by duythien** [prometheus/mysqld_exporter#475]
**What did you do?**
Monitor mysql 8.0.x on azure
**What did you expect to see?**
See data
**What did you see instead? Under which circumstances?**
invalid metric type "ocap_thrcnt_limit untyped"
**Environment**
Use AKS on azure

* System information:

* Prometheus version:

	
![image](https://user-images.githubusercontent.com/1762691/83233191-8bd0e900-a1b8-11ea-8821-df1c8c44e501.png)

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
prometheus.yml:
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml
    ## Below two files are DEPRECATED will be removed from this default values file
      - /etc/config/rules
      - /etc/config/alerts

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
      - job_name: 'mysql-dev'
        static_configs:
          - targets:
            - prometheus-mysql-exporter:9104 
            labels:
              alias: db1# alias name given to this instance
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=warn ts=2020-05-29T07:24:06.440Z caller=scrape.go:972 component="scrape manager" scrape_pool=mysql-dev target=http://prometheus-mysql-exporter:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:24:35.708Z caller=scrape.go:972 component="scrape manager" scrape_pool=kubernetes-pods target=http://10.244.0.102:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:25:06.435Z caller=scrape.go:972 component="scrape manager" scrape_pool=mysql-dev target=http://prometheus-mysql-exporter:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:25:35.691Z caller=scrape.go:972 component="scrape manager" scrape_pool=kubernetes-pods target=http://10.244.0.102:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:26:06.437Z caller=scrape.go:972 component="scrape manager" scrape_pool=mysql-dev target=http://prometheus-mysql-exporter:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:26:35.699Z caller=scrape.go:972 component="scrape manager" scrape_pool=kubernetes-pods target=http://10.244.0.102:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:27:06.462Z caller=scrape.go:972 component="scrape manager" scrape_pool=mysql-dev target=http://prometheus-mysql-exporter:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:27:35.687Z caller=scrape.go:972 component="scrape manager" scrape_pool=kubernetes-pods target=http://10.244.0.102:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:28:06.438Z caller=scrape.go:972 component="scrape manager" scrape_pool=mysql-dev target=http://prometheus-mysql-exporter:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""
level=warn ts=2020-05-29T07:28:35.715Z caller=scrape.go:972 component="scrape manager" scrape_pool=kubernetes-pods target=http://10.244.0.102:9104/metrics msg="append failed" err="invalid metric type \"ocap_thrcnt_limit untyped\""

```
