### ISSUE TITLE
Build Context Missing 

### ISSUE THREAD

**Issue by baebae-dev** [prometheus/mysqld_exporter#667]
I ran a mysqld-exporter on kubernets
i write a yaml descript like this
```
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: monitoring
  labels:
    app: mysqld-exporter
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9104
      protocol: TCP
  selector:
    app: mysqld-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: monitoring
  labels:
    app: mysqld-exporter
spec:
  selector:
    matchLabels:
      app: mysqld-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:latest
          env:
            - name: DATA_SOURCE_NAME
              value: {{user}}:{{pwd}}@tcp({{host}}:{{port}})/
          ports:
            - containerPort: 9104
```

### MySQL server version
MySQL is up on PM

and when i apply this yaml
pod log look like this
**"level=info msg="Build context" (gogo1.17.8,userroot@401d370ca42e,date20220304-16:25:15)=(MISSING)"**
<img width="1392" alt="스크린샷 2022-09-22 오후 2 25 19" src="https://user-images.githubusercontent.com/52961872/191665040-c09e5029-5a91-4ba6-9a28-7b0654809b96.png">

i want to any help about this!
why build context is Missing
what is meaning and how can i troubleshooting

thanks many
