### ISSUE TITLE
Multiple Targets Mysql using Kubernets

### ISSUE THREAD

**Issue by alexandrempm** [prometheus/mysqld_exporter#694]
Is there some example of the manifest to monitor multiples targets, using mysql_exporter on Kubernetes?

I tried to use this manifest without success:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter-prometheus-mysql-exporter
  labels:
    helm.sh/chart: prometheus-mysql-exporter-1.9.1
    app.kubernetes.io/name: prometheus-mysql-exporter
    app.kubernetes.io/instance: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-mysql-exporter
      app.kubernetes.io/instance: mysql-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-mysql-exporter
        app.kubernetes.io/instance: mysql-exporter
      annotations:
        checksum/credentials: bf500afd8dbfc2cd77011d8cdcd36917992fdc0abd30b52106db3e827d42520c
        prometheus.io/path: /metrics
        prometheus.io/port: "9104"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: prometheus-mysql-exporter
          securityContext:
            {}
          image: "prom/mysqld-exporter:v0.14.0"
          imagePullPolicy: IfNotPresent
          args:
            - "--collect.binlog_size"
            - "--collect.global_status"
            - "--collect.global_variables"
            - "--collect.info_schema.tables"
            - "--collect.slave_status"
          ports:
            - containerPort: 9104
          livenessProbe:
            httpGet:
              path: /
              port: 9104
          readinessProbe:
            httpGet:
              path: /
              port: 9104
          resources:
            {}
          volumeMounts:
          - name: mysql-conf
            mountPath: "/home"
            readOnly: true
      volumes:
      - name: mysql-conf
        secret:
          secretName: mysql-exporter-prometheus-mysql-exporter
          items:
          - key: mysql-conf
            path: .my.cnf
```

Secret:

```
[client]
user = XXXXXXX
password = XXXXXX
```

Job
```
- job_name: mysql
  params:
    auth_module: client
  static_configs:
    - targets:
      -XXXXXXXXX:3306
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: host 
```
