### ISSUE TITLE
hard to trounbleshooting scrape error when using multi target scrape

### ISSUE THREAD

**Issue by LeoQuote** [prometheus/mysqld_exporter#713]
### Host operating system: output of `uname -a`
not relevant
### mysqld_exporter version: output of `mysqld_exporter --version`

```
mysqld_exporter, version 0.14.0 (branch: main, revision: 530e351d293dd632f31b80947f5ca420ef17adaf)
  build user:       root@db8fcefbf4c4
  build date:       20221209-17:58:51
  go version:       go1.19.4
  platform:         linux/amd64
```
### MySQL server version
not relevant
### mysqld_exporter command line flags

```
  --web.listen-address=":9104" \
  --config.my-cnf=/etc/mysqld-exporter/my.cnf \
  --collect.heartbeat \
  --collect.heartbeat.database=dba
```
### What did you do that produced an error?
setup a exporter and scrape using `/probe` endpoint 

```
    - job_name: all-mysql
      scheme: http
      metrics_path: "/probe"
      http_sd_configs:
      - url: "http://my-sd/sd"
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: my-exporter:9104
```
### What did you expect to see?
when scrape failed, detailed log should be shown to guide me , including:
* connections string
* sql query that are using

and mysql_exporter_last_scrape_error should be isolated between scrapes , if there's multiple scrape at the same time , the mysql_exporter_last_scrape_error  would be mixed.
### What did you see instead?
* the error log is not detailed enough  : `2023-03-06 17:15:17.681301500 ts=2023-03-06T09:15:17.680Z caller=exporter.go:174 level=error msg="Error from scraper" scraper=heartbeat err="Error 1146: Table 'dba.heartbeat' doesn't exist"`
* when scrapes are close in time, they almost occur at the same time, `mysql_exporter_last_scrape_error ` would be mixed, I'm not confident about it .

```
      rate(mysql_exporter_scrape_errors_total[1m]) 
      * on(instance) group_left()
      mysql_exporter_last_scrape_error > 0
```
I'm using this rule to alert me when there's scrape error, what I assumed is that the mysql_exporter_last_scrape_error is perfectly accurate and it shows exactly scrape I'm conducting, so this wont be a false alarm.

but the truth is that there is constantly false alarm for instance that scraping errors cannot be reproduced. my guess is that the metric is shared in the whole exporter instance so it can be set by other scrapes.
