### ISSUE TITLE
Mysql clear text password error on gcp kubernetes with sql proxy and workload identity

### ISSUE THREAD

**Issue by jozsoka2222** [prometheus/mysqld_exporter#785]
Hi guys,
I have a little error with my mysqld-exporter on gcp kubernetes with cloud-sql proxy and workload identity.

mysqld-exporter version: 0.15.0
helm-chart version: 2.1.0

I install with helm use this config:

```
# mysql connection params which build the DATA_SOURCE_NAME env var of the docker container
mysql:
  db: ""
  host: "localhost"
  additionalConfig:
    - allowCleartextPasswords=true
  pass: ""
  port: 3306
  protocol: ""
  user: "mysqld-exporter"
  # secret with full DATA_SOURCE_NAME env var as stringdata
  existingSecret: ""
  # secret only containing the password
  existingPasswordSecret:
    name: ""
    key: ""

# cloudsqlproxy https://cloud.google.com/sql/docs/mysql/sql-proxy
cloudsqlproxy:
  enabled: true
  image:
    repo: "us.gcr.io/cloud-sql-connectors/cloud-sql-proxy"
    tag: "2.7.0-alpine"
    pullPolicy: "IfNotPresent"
  instanceConnectionName: "cluster-staging:us-east1:staging-sql"
  privateIp: true
  port: "3306"
  credentialsSecret: ""
  # service account json
  credentials: ""
  workloadIdentity:
    enabled: true
    serviceAccountEmail: "mysqld-exporter@cluster-staging.iam.gserviceaccount.com"
  extraArgs: ""
```

And I am getting the following error message:

`Error pinging mysqld" err="this user requires clear text authentication. If you still want to use it, please add 'allowCleartextPasswords=1' to your DSN`

In my system setup I want to use workload identity and the following values configuration does not work  either.

```
mysql:
  db: ""
  host: "localhost"
  additionalConfig:
    - MYSQL_ENABLE_CLEARTEXT_PLUGIN=true
 ```

Please suggest what is the proper way of forcing `cleartext password` authentication

Thanks a lot!
