### ISSUE TITLE
MYSQLD_EXPORTER_PASSWORD cannot be parsed correctly

### ISSUE THREAD

**Issue by hzfq** [prometheus/mysqld_exporter#821]
i am using mysqld-exporter by docker compose, my docker-compose.yml is

```
version: "3"
services:
  mysql-exporter:
    image: prom/mysqld-exporter:v0.15.1
    container_name: mysql-exporter
    restart: always
    privileged: true
    user: root
    networks:
      - default
    ports:
      - 39104:9104
    environment:
      MYSQLD_EXPORTER_PASSWORD: 'xx$kXxxxx*abc'
    command:
      - "--mysqld.address=localhost:3306"
      - "--mysqld.username=root"
networks:
  default:
    driver: bridge
```

when i am starting with docker compose up -d, occuring error like following
```
WARN[0000] The "kBl9DVR" variable is not set. Defaulting to a blank string.
```

in addition, i am tried "xx\$kXxxxx*abc", but error still exist,
```
parsing /opt/mysql-exporter/docker-compose.yml: yaml: line 14: found unknown escape character
```

so, how to add password of mysql to mysqld-exporter?
