### ISSUE TITLE
My MySQL connection status is normal but mysql_up == 0

### ISSUE THREAD

**Issue by kyungminchoi** [prometheus/mysqld_exporter#933]
hello, 
I am trying to connect to many databases from one server. 

When I check directly on the server, all database connections are **normal**.
However, mysql exporter shows most of them as **mysql_up==0**.

Here are the items I checked ((The results are normal for all targets.)):

1. `mysql -h10.162.5.64 -P13306  -ucert_manager_dev -pxxx!@#`
2. SELECT 1;
3. SHOW GLOBAL STATUS;
4. SHOW VARIABLES;

Note that some targets have the same IP but different users.
I deployed the exporter to kubernetes using [helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-mysql-exporter).

Here are my target information:
```
  multipleTarget:
    enabled: true
    targets: 
      # target connection information with name (required), endpoint (required), port (optional), user(optional), password(optional)
      - name: Certificate Manager
        endpoint: 10.162.5.64
        port: 13306
        user: cert_manager_dev
        password: "xxx!@#123"
      - name: Security Advisor
        endpoint: 10.162.5.188
        port: 13306
        user: advisor_alpha
        password: "xxx!@#"
      - name: Security Compliance
        endpoint: 10.162.5.64
        port: 13306
        user: tc_cg_dev
        password: "C@dev!xxx"
      - name: Security Bastion
        endpoint: 10.162.5.64
        port: 13306
        user: bastion_alpha
        password: "xxx!@#123"
      - name: Security Bastion (Alpha-Real)
        endpoint: 10.162.5.64
        port: 13306
        user: bastion
        password: "xxx!@#123"
      - name: Marketplace API
        endpoint: 10.162.5.64
        port: 13306
        user: marketplace
        password: "xxx!234"
      - name: CDN
        endpoint: 10.162.5.188
        port: 13306
        user: cdn
        password: "xxx!@#123"
      - name: AI Easymaker
        endpoint: 10.162.5.188
        port: 13306
        user: easymaker
        password: "xxx!@#123"  
      - name: Scheduler
        endpoint: 10.162.5.59
        port: 13306
        user: scheduler
        password: "xxx*()890"            
      - name: Scheduler (Airflow)
        endpoint: 10.162.5.59
        port: 13306
        user: airflow
        password: "xxx*()890"     
      - name: DNS Plus
        endpoint: 10.162.5.64
        port: 13306
        user: dns_plus
        password: "xxx!@#"
      - name: Deploy (내부)
        endpoint: 10.162.5.188
        port: 13306
        user: tcdeploy
        password: "xxx@#xxx"
      - name: Deploy (외부)
        endpoint: 10.162.5.188
        port: 13306
        user: tcdep_ext_alpha
        password: "xxx!@#321"
      - name: Network Firewall
        endpoint: 10.162.5.188
        port: 13306
        user: nfw_alpha
        password: "xxx!@#123"
      - name: Network Firewall (alpha2)
        endpoint: 10.162.5.188
        port: 13306
        user: nfw_alpha2
        password: "xxx!@#123"
      - name: Network Firewall (task_alpha1)
        endpoint: 10.162.5.188
        port: 13306
        user: nfw_task_alpha1
        password: "xxx!@#123"
      - name: Secure Key Manager
        endpoint: 10.162.5.64
        port: 13306
        user: kms
        password: "xxx#$%"
      - name: NHN Cloud Access
        endpoint: 10.162.5.64
        port: 13306
        user: c2svpn_alpha
        password: "xxx!@#"
      - name: NHN Cloud Access (auth)
        endpoint: 10.162.5.64
        port: 13306
        user: ac_auth_alpha_kr1
        password: "xx!"
      - name: NHN Cloud Access (kc)
        endpoint: 10.162.5.64
        port: 13306
        user: ac_kc_alpha_kr1
        password: "xxx!"
      - name: NHN Cloud Access (policy)
        endpoint: 10.162.5.64
        port: 13306
        user: ac_policy_alpha_kr1
        password: "xxx!"
      - name: NHN Cloud Access (pdp)
        endpoint: 10.162.5.64
        port: 13306
        user: pdp
        password: "xxx#"
      - name: DDoS Guard
        endpoint: 10.162.5.64
        port: 13306
        user: ddos
        password: "xxx!@#123"
```

Among these, the targets with mysql_up==1 are Scheulder, Scheduler(Airflow), Marketplace API, and Security Compliance.
I don't know what the difference is between them, so please let me know what else I should check.

Here is the log of my mysql exporter.
```
time=2025-03-11T02:40:03.090Z level=ERROR source=mysqld_exporter.go:174 msg="Failed to parse section [client] from config file" err=<nil>
time=2025-03-11T02:40:03.092Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="dial tcp 127.0.0.1:3306: connect: connection refused"
time=2025-03-11T02:40:03.286Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'cert_manager_dev'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:05.406Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'nfw_alpha2'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:05.736Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'nfw_task_alpha1'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:12.576Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'pdp'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:13.616Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'dns_plus'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:13.744Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'cdn'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:14.594Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'kms'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:14.657Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'c2svpn_alpha'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:16.098Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'tcdeploy'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:16.759Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'ac_policy_alpha_kr1'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:17.169Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'bastion_alpha'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:17.185Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'bastion'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:20.411Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'tcdep_ext_alpha'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:22.861Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'advisor_alpha'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:25.409Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'ac_auth_alpha_kr1'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:25.741Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'ac_kc_alpha_kr1'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:29.979Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'ddos'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:30.575Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'nfw_alpha'@'10.162.4.84' (using password: YES)"
time=2025-03-11T02:40:32.109Z level=ERROR source=exporter.go:131 msg="Error opening connection to database" err="Error 1045 (28000): Access denied for user 'easymaker'@'10.162.4.84' (using password: YES)"
```
