### ISSUE TITLE
No connect to MySQL

### ISSUE THREAD

**Issue by SokolSec** [prometheus/mysqld_exporter#954]
Hello! 
**docker-compose.yml**
```
version: '3'
services:

  mysql-exporter:
    image: prom/mysqld-exporter:v0.15.1
    command:
     - --config.my-cnf=/cfg/.my.cnf
     - --collect.engine_innodb_status
     - --collect.info_schema.clientstats
     - --collect.info_schema.innodb_cmp
    volumes:
      - /opt/mysqld-exporter/.my.cnf:/cfg/.my.cnf
    ports:
      - 9104:9104
```
**.my.cnf**
```
[client]
host=**********
port=3306
user=************
password=***************
```

**error logs**
ts=2025-05-07T08:58:30.037Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9104
ts=2025-05-07T08:58:47.898Z caller=exporter.go:152 level=error msg="Error pinging mysqld" err="Error 1045 (28000): Access denied for user '******t'@'******' (using password: YES)"
ts=2025-05-07T08:58:51.049Z caller=exporter.go:152 level=error msg="Error pinging mysqld" err="Error 1045 (28000): Access denied for user '******t'@'******' (using password: YES)"

What is the problem, please help?
